# The URL the site will be built for
base_url = "https://knz.ai"
title = "Kenzi Connor"
description = "Staff software engineer - VP Engineering - Director of Engineering - CEO & CTO"
compile_sass = true
build_search_index = true

[markdown]
highlight_code = true

[extra]
color_theme = "theme-base-08"
sidebar_reverse = true
sidebar_links = [
    {url = "https://github.com/knzai", name = "GitHub"},
    {url = "https://www.linkedin.com/in/knzai/", name = "LinkedIn"},
    {url = "mailto:site@knz.ai", name = "site@knz.ai"},
    {url = "/assets/Kenzi Connor Resume.pdf", name = "resume.pdf"},
]
sidebar_sticky = true