on: 
  push:
    branches:
      - main     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: download assets
      shell: bash
      run: "./get_gdrive_files.sh gdrive_files.csv"
      env:
        GAPI_KEY: ${{secrets.GOOGLE_API_KEY}}
    - uses: zolacti/on@main