on: 
  push:
    branches:
      - main     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: download gdrive files
      shell: bash
      run: |
        curl -s -L https://gist.github.com/knzai/75702a336a25646e6c0039f96d5732b9/raw > ggdrive.sh
        bash ggdrive.sh gdrive_files.csv
      env:
        GAPI_KEY: ${{secrets.GOOGLE_API_KEY}}
    - uses: zolacti/on@main